# Lightning Lesson 2: Task Configurations
# Advanced Agent Persona Architecture

# Marketing Tasks
product_launch_email:
  description: "Write a product launch email for our new AI-powered customer service tool"
  expected_output: "A compelling, brand-aligned product launch email that drives engagement and conversions"
  context: "Target audience: B2B SaaS companies, Budget: $50K, Timeline: 2 weeks"
  agent: "creative_marketing_agent"

social_media_strategy:
  description: "Create a social media strategy for our tech startup"
  expected_output: "A comprehensive social media strategy with platform-specific tactics and content calendar"
  context: "Startup stage: Series A, Target: B2B decision makers, Budget: $10K/month"
  agent: "creative_marketing_agent"

brand_positioning:
  description: "Design a brand positioning strategy for our B2B SaaS product"
  expected_output: "A clear brand positioning framework with messaging pillars and competitive differentiation"
  context: "Market: Customer service software, Competitors: Zendesk, Intercom, Freshdesk"
  agent: "creative_marketing_agent"

# Legal Tasks
privacy_policy_review:
  description: "Review our data privacy policy for compliance issues"
  expected_output: "A comprehensive compliance review with identified risks and recommended actions"
  context: "Company: Tech startup, Data: User behavior analytics, Jurisdiction: EU + US"
  agent: "legal_compliance_agent"

terms_of_service_review:
  description: "Review our terms of service for potential legal risks"
  expected_output: "A detailed legal risk assessment with specific recommendations for improvement"
  context: "SaaS platform, B2B customers, International operations"
  agent: "legal_compliance_agent"

data_processing_agreement:
  description: "Draft a data processing agreement for our EU customers"
  expected_output: "A GDPR-compliant data processing agreement with all required clauses"
  context: "GDPR compliance, EU customers, Data processing activities"
  agent: "legal_compliance_agent"

# Technical Tasks
microservices_architecture:
  description: "Design a microservices architecture for our e-commerce platform"
  expected_output: "A detailed technical architecture with service definitions, APIs, and deployment strategy"
  context: "Scale: 100K users, Features: Payment, inventory, recommendations, Timeline: 6 months"
  agent: "technical_lead_agent"

security_audit:
  description: "Conduct a security audit of our authentication system"
  expected_output: "A comprehensive security assessment with vulnerabilities and remediation plan"
  context: "OAuth 2.0 implementation, Multi-tenant SaaS, High-security requirements"
  agent: "technical_lead_agent"

disaster_recovery_plan:
  description: "Create a disaster recovery plan for our cloud infrastructure"
  expected_output: "A detailed disaster recovery plan with RTO/RPO targets and implementation procedures"
  context: "AWS infrastructure, Multi-region deployment, 99.9% uptime requirement"
  agent: "technical_lead_agent"

# Comparison Tasks (for before/after demo)
comparison_email_task:
  description: "Write a product launch email for our new AI tool"
  expected_output: "A professional product launch email that demonstrates persona differences"
  context: "Generic task to show default vs persona-engineered responses"
  agent: "default_marketing_agent"

comparison_persona_task:
  description: "Write a product launch email for our new AI tool"
  expected_output: "A brand-aligned, persona-engineered product launch email"
  context: "Same task as comparison_email_task but with persona-engineered agent"
  agent: "comparison_marketing_agent"
