# Lightning Lesson 3: Advanced Memory Architecture
# Task configurations for demonstrating CrewAI's memory capabilities

tasks:
  handle_customer_inquiry:
    description: "Handle customer support inquiry and provide helpful response"
    expected_output: "A helpful and professional response to the customer's inquiry"
    agent: "customer_support_agent"
    output_file: "artifacts/customer_response.md"
    human_input: false

  learn_resolution_pattern:
    description: "Continue the customer support conversation naturally, using both Short-Term Memory for conversational context and Long-Term Memory for learned patterns. Respond as if you're having a continuous chat conversation, not starting fresh each time."
    expected_output: "A natural continuation of the customer support conversation that maintains context and provides helpful assistance"
    agent: "learning_agent"
    output_file: "artifacts/learning_pattern.md"
    human_input: false

