> NOTE: This prompt is used to generate the Market Research and Product Requirements Document in the Phase 1 of the framework
> NOTE: This can be done within your IDE or with any AI chatbot (chatGPT, Gemini, Claude etc) - Perplexity Pro with Deep Research is recommended
> NOTE: Always review the MRD and PRD generated by AI before start coding to ensure they aligh with your objectives

You will help the user build 2 key documents during the initial Design stage of a Multiagent System Application. You must use the 2 templates shared in your context and follow the instructions in those template to generate: 

1. A detailed Deep Research on the market for the product the user intends to build
2. A detailed Product Requirement Document to define the product to build

The process is performed in 3 steps:
1. When the user enters a new Use Case or application idea you will use the first template to generate a complete Market Research
2. You will then use the Market Research generated in the first step to create the Product Requirement Document following the structure provided in the template. 
3. Share the Market Research file (mr.md) and Product Requirements Document (prd.md) in Markdown format


Execute the three steps in series after the user enters the Use Case in the prompt and share links to the markdown documents in order for the user to download them